### ISSUE TITLE
Missing mouse + modification key + some idea )

### ISSUE THREAD

**Issue by mike2003** [brookhong/brookhong.github.io#14]
Imagine that I did not need to see the usual mouse click.
But it is necessary to see if the mouse button is pressed together with the ALT, or SHIFT or CTRL. Disable "mouse action" and now i see only (for example) CTRL ONLY! when releasing the button.

1 Can add the option to display the buttons on the mouse only together with other modifiers?
2 Combine the UP and DOWN for mouse if they are very fast (in the settings create option for time)
3 Add a bit of space on the side. To balance the bottom and top.
4 Add the ability to see UP or DOWN for ctrl/alt/shift. Now I do not see actual moment of pressing the button. 
![mouse01](https://cloud.githubusercontent.com/assets/11754198/6941318/85607c20-d887-11e4-969e-32ae4503d3b7.jpg)
![hk-side](https://cloud.githubusercontent.com/assets/11754198/6941385/33b58680-d888-11e4-8c6e-217969028448.jpg)
At the moment, the program does not have enough possibilities to show ALT-CTRL-SHIFT buttons with mouse action (like CTRL+drag without many single mouse click). Perhaps show (and stay on screen UP while pressing) the moment of pressing (UP and DOWN) for ALT-CTRL-SHIFT without mouse button.
![mouse-vip](https://cloud.githubusercontent.com/assets/11754198/6941691/aa0b6e38-d88a-11e4-92e6-9a3a710b2c50.jpg)
PS
nice app!

**Comment by brookhong** [comment]
Thanks for feedback, please download 2.0.0.9.

> 1 Can add the option to display the buttons on the mouse only together with other modifiers?

Check the box -- Mouse Only With Modifier

> 2 Combine the UP and DOWN for mouse if they are very fast (in the settings create option for time)

Have a try

I'm afraid that I did not get your points on number 3, 4.

**Comment by mike2003** [comment]
My Action: CTRL+LMB
but after click i see unnecessary additional line of text
http://i.imgur.com/J33TFHD.jpg

**Comment by brookhong** [comment]
@mike2003 please open the settings dialog to uncheck the box -- Display Standalone Modifier Key.

**Comment by mike2003** [comment]
for example - in photoshop i use CTRL (Press and hold) for some guide on screen. but keycastow dont show this key. only when release

**Comment by mike2003** [comment]
What do you think about this? :) Possible?

**Comment by brookhong** [comment]
Please download 2.0.1.0, and tweak your settings as the screenshot
![image](https://cloud.githubusercontent.com/assets/288207/7118510/5521c5c8-e232-11e4-9f48-4a1530ab4ddf.png)
It's the best settings that I can think of for your case.
In 2.0.1.0, the standalone modifiers are displayed when they're pressed down.

**Comment by mike2003** [comment]
now problem with holding modifier. spam appears at the output.
need Auto Repeta disabled for modifier keys.
