### ISSUE TITLE
建议按键按下时只显示一次

### ISSUE THREAD

**Issue by lxfly2000** [brookhong/brookhong.github.io#15]
有三个问题
1. 这个软件我主要用来演示游戏操作，但是很多游戏中经常出现一个键要按很久的情况（比如按Z射击，按方向键移动等等），结果整个屏幕就有一大串的Z和方向键，于是建议增加一个选项，在按键按下的时候无论按的时间有多久，只要在按下时出现一个就够了，不要刷出那么一大长条的按键
![image](https://cloud.githubusercontent.com/assets/11847274/7039643/7cec86fe-ddf7-11e4-996f-808d2f2c11d0.png)
2. 我把 Label Spacing 改成 0 时感觉两行间还是有点稀疏，后来改成了 -1, 然后 Save，结果程序崩溃，系统提示【keystroke visualizer for Windows,  lets you easily display your keystrokes while recording screencasts. 已停止工作】，鼠标、键盘均无响应（但是系统并没有卡死），无奈只好重启电脑，结果重启后连程序都打不开直接就停止工作了（现在仍没能打开），我估计可能是因为不支持负数导致的，想清空一下设置也不知道配置文件在哪。（放在注册表里了吗？如果是这样我觉得把设置保存在一个文件里比较好）
3. 能不能做个中文界面？（当初下载时我还以为又是老外写的软件呢）

**Comment by brookhong** [comment]
谢谢，你的一些建议很好。
这个需求有人提过https://github.com/brookhong/brookhong.github.io/issues/9，最近会实现。
中文界面优先级不高，以后再说，因为老外用户比较多，而且设置还比较简单。

**Comment by lxfly2000** [comment]
还有一点功能建议，就是增加对齐方式，让那些文字可以在右下角、左上角、右上角等等显示

**Comment by brookhong** [comment]
试下最新版本2.0.1.0，解决了1和2。把`Keyboard Auto Repeat`的勾去掉，按住a不放，只会触发一个a，只有当放开之后再按下a，才会出现下一个a。 
另外设置都存在 HKEY_CURRENT_USER\Software\KeyCastOW

**Comment by lxfly2000** [comment]
谢谢！

**Comment by brookhong** [comment]
2.0.2.0, 已经实现了 右对齐。
