### ISSUE TITLE
Get rid of fast switching mouse DOWN -> CLICK

### ISSUE THREAD

**Issue by mike2003** [brookhong/brookhong.github.io#19]
perhaps...
Make a slight delay (to determine process) when outputting posts about a mouse click, that would not have this switch!
MouseDOWN -> CLICK
![clicks](https://cloud.githubusercontent.com/assets/11754198/7346050/467cdd30-ece3-11e4-9254-9b4cfd8e1aca.gif)

**Comment by jheom9** [comment]
c
