### ISSUE TITLE
How to disable brackets?

### ISSUE THREAD

**Issue by mike2003** [brookhong/brookhong.github.io#21]
How to disable brackets?
http://i.imgur.com/BB0kL1i.jpg
I've tried "comb. chars" to " + "
but this not workes
and after restart " + " changed to "+"
and app began to fail

**Comment by brookhong** [comment]
please try 2.0.2.3.
remove the 3rd char of Combination Chars to disable brackets

Thanks

**Comment by mike2003** [comment]
sorry, I can not understand or is not working. everything remains as before
