### ISSUE TITLE
Broken Position

### ISSUE THREAD

**Issue by mike2003** [brookhong/brookhong.github.io#22]
After restart keycastow loses position.
It only works after setting and reset at start.
everything worked well before 2.0.2.1
I displayed tips on a second monitor
in my case, they move out to the side and can not see them! (red arrow)
![shifting](https://cloud.githubusercontent.com/assets/11754198/7536195/6cbfdd88-f596-11e4-9318-937268e74079.jpg)

**Comment by brookhong** [comment]
Fixed in 2.0.2.2
