### ISSUE TITLE
Turn on-off toggles

### ISSUE THREAD

**Issue by delorean1988** [brookhong/brookhong.github.io#25]
1. It would be nice to make the ability to disable text formatting Components <>
2. It was also good to make the ability to disable LButtonUp, Down, and so on. just keep LButtonClick, MButtonClick, RButtonClick. And maybe will be good so add "hold" identificators - "LButtonClick (hold)"
3. Maybe I have a problem with windows, maybe the program have a bug. Try to open a text document  for example, and hold any letter on the keyboard. In my case will be displayed just one letter. Program locks pressed letter-keys in windows. Something like this.

Hopefully could normally to explain

Thank you very much for such a wonderful program. The best for  hotkeys display!

**Comment by brookhong** [comment]
1. please try 2.0.2.3, remove the 3rd char of Combination Chars to disable brackets
1. will think about it if there were more requests.
1. Do you turn off `Hold Down to Repeat` option from settings?

Thanks

**Comment by delorean1988** [comment]
1. Yep it works, thanks!
2. It would be nice
3. Accidentally disabled this checkbox. My fault. Thanks!

**Comment by brookhong** [comment]
Fixed in 2.0.2.5
