### ISSUE TITLE
Mouse pressing disappear before release.

### ISSUE THREAD

**Issue by tohnperfect** [brookhong/brookhong.github.io#27]
Now LButtonDown and RButtonDown just show once and fade away. 
Is it possible to make it showing while the button is pressing?

**Comment by brookhong** [comment]
Are you using the latest version?
2.0.2.3 works in that way.

**Comment by tohnperfect** [comment]
Yes, i'm using the newest version, with scrolling up or down.

**Comment by brookhong** [comment]
Turn on `Detect Click/DblClick` from settings, then try it.

**Comment by brookhong** [comment]
Turn on `Detect Click/DblClick` from settings, then try it.

**Comment by tohnperfect** [comment]
Excellent!, It works perfectly now.
Any chance that you will make it works in the same way without Click/DblClick?
