### ISSUE TITLE
咨询KeyCastOW 和 LICEcap 录制gif的方法

### ISSUE THREAD

**Issue by yqu212** [brookhong/brookhong.github.io#31]
你好，我使用你的KeyCastOW 和 LICEcap 尝试录制gif，但是没有成功。得到的gif里面没有捕捉KeyCastOW显示的按键。网上没有搜索到相关的信息，能否提示一下应该怎么做？

**Comment by brookhong** [comment]
这里面没有什么特别的，只要你的按键KeyCastOW能显示出来，LICEcap就能捕捉到的。你先确认LICEcap不启动时，KeyCastOW能不能显示你的按键。

**Comment by yqu212** [comment]
KeyCastOW是正常工作的，不管LICEcap是否启动。我使用的两个软件都是最新版本。我注意到一个情况，在录制时KeyCastOW显示的按键会遮挡LICEcap的窗口。不知道与这有没有关系？

**Comment by brookhong** [comment]
LICEcap的窗口中间是空的（透明的），只有在那个区域里的才会被录制。所以你要保证按键显示在那个区域。

**Comment by yqu212** [comment]
我没有犯这样的错。但是确实捕捉不到按键。
