### ISSUE TITLE
Keystroke delay in configuration file

### ISSUE THREAD

**Issue by Solksjaer** [brookhong/brookhong.github.io#35]
Hello,
after changing the keystroke delay setting, saving and then closing the program, your previously defined keystroke delay will be overwritten by the standard configuration.
By showing the "keycastow.ini" there is no configuration value for this attribute, therefore the configs are not saved and, logically, not loaded by re start.
Thanks!

**Comment by brookhong** [comment]
Thanks.
It is a bug, fixed in 2.0.2.4.

**Comment by Solksjaer** [comment]
Thanks for the fast reply/solve !!
