### ISSUE TITLE
Extensible Key Exclusion System

### ISSUE THREAD

**Issue by phohale** [brookhong/brookhong.github.io#39]
I'm requesting a simple but universal solution to the common problem of excluding an undesired key from display. Instead of having to anticipate all possible exclusions a user may want, I propose a simple blacklist approach that allows the user to specify keys to exclude using the name that appears when they are pressed.

To both clarify what I propose, and demonstrate the demand for such a feature, I have constructed potential "blacklists" that would solve the problems presented in other issues:

| Issue | Potential Blacklist String |
| --- | --- |
| Myself | {Delete, Enter, Backspace, Space, ...} |
| #28 | {LButtonUp, RButtonUp, ...} |
| #25 | {LButtonUp, Down, ...} |

Thank you for constructing such a great program, and for your time maintaining it. If the program was open source I would be more than willing to implement the functionality myself, but sadly it isn't.

**Comment by Denyerec** [comment]
Being driven slowly insane by <Space> and <Enter> being captured...

**Comment by brookhong** [comment]
Open source now. https://github.com/brookhong/KeyCastOW
