### ISSUE TITLE
Keycast flagged as virus by Nod32

### ISSUE THREAD

**Issue by dcarapic** [brookhong/brookhong.github.io#49]
Hi,
I just wanted to try out your KeyCast app and my AV flagged it as a virus.

![2016-10-06_090911](https://cloud.githubusercontent.com/assets/5895972/19143562/09826758-8ba5-11e6-8d4a-a2da27d4a284.png)

My AV version:

![2016-10-06_091308](https://cloud.githubusercontent.com/assets/5895972/19143572/207b20d0-8ba5-11e6-9c46-64a207317a6c.png)

**Comment by brookhong** [comment]
Keycastow uses keyboard hook, it's possible that some AV treat it as virus.

I'm sorry, but I can not help on this.

You could contact with your AV vendor about this.

**Comment by dcarapic** [comment]
Well,
you are the author. Usually the author takes care of it but it is your
choice.
I simply wanted to let you know so that you might want to take care of it.
I just used another program.

-- 
Dalibor Čarapić

**Comment by brookhong** [comment]
Thanks for information.

**Comment by brookhong** [comment]
#54 #
