### ISSUE TITLE
Windows Defender identifies keycastow as Win32/Rundas!plock trojan.

### ISSUE THREAD

**Issue by nanodeath** [brookhong/brookhong.github.io#54]
Windows Defender now automatically deletes keycastow, as it thinks it contains [this trojan](https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fRundas!plock&threatid=2147711527&enterprise=0).

**Comment by PascalRiekenberg** [comment]
Also McAfee complains about a trojan horse (RDN/Generic.dx) inside keycastow.

**Comment by raffi98** [comment]
same with avast : win32:trojan-gen
it triggers 22 antiviruses on 55 on virustotal
mbam doesnt detect harm though

**Comment by 2220209876** [comment]
eset也报毒。。
![snipaste20161230_234008](https://cloud.githubusercontent.com/assets/7346652/21567732/58b527fc-cee9-11e6-9c87-1d63482e980f.png)
。

**Comment by JohnGlassmyer** [comment]
Firefox blocks access to the site, http://brookhong.github.io, as an "Unwanted Software Site".

And ESET blocks downloading keycastow.zip for "a variant of Generik.QTCQRL trojan".

**Comment by brookhong** [comment]
Thanks all for reporting this.

I just have had time to set up my windows desktop with Windows 10, and reproduced the issue. Rebuild it on Windows 10 with Visual Studio 2015 seems to fix it.

**Comment by horusra** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/17074394/24996275/8d388394-2032-11e7-916b-2ec09b96f825.jpg)

**Comment by avogelba** [comment]
https://www.virustotal.com/en/file/a454ff0b9bbceeb319835a8715e454a82498f24594b7d59eafebbe0891968332/analysis/1493142264/

https://www.hybrid-analysis.com/sample/227070fc2a71ce2b3cdf9cbce14d01b2d6a8d04b7a3d98f7e2c44862496a25c7?environmentId=100

Probably false alarms due usage of hook api, but due lack of source code can´t be verified

**Comment by David-Bates** [comment]
I just came back to https://brookhong.github.io/2014/04/28/keycast-on-windows.html and FireFox is blocking it again (or still). Don't know if related or not, but it also is not showing up in google search results.

**Comment by yogan** [comment]
Same for me. @brookhong: can't you open source this application, so we can check the code?

**Comment by brookhong** [comment]
Open source now. https://github.com/brookhong/KeyCastOW

**Comment by yogan** [comment]
Awesome, thank you so much!
