### ISSUE TITLE
醉了，原版报毒。。。民间汉化版竟然不报毒了

### ISSUE THREAD

**Issue by 2220209876** [brookhong/brookhong.github.io#57]
![snipaste20161230_234008](https://cloud.githubusercontent.com/assets/7346652/21567938/386fd044-ceeb-11e6-80cc-42b293f65a6d.png)

**Comment by brookhong** [comment]
:(

能告诉我报毒的KeyCastow版本和未报毒的民间汉化版各自的版本号吗？我有时间的时候看看。

**Comment by 2220209876** [comment]
[keycastow 汉化未报毒.zip](https://github.com/brookhong/brookhong.github.io/files/679489/keycastow.zip)
附件里是汉化未报毒的，报毒的是在这里下载的最新版  杀毒软件eset

**Comment by guohongci** [comment]
从google进入https://brookhong.github.io/2014/04/28/keycast-on-windows.htm这个页面也遇到安全警告。

**Comment by brookhong** [comment]
#54
