### ISSUE TITLE
Feature Request: Ignore keyboard repeat interval

### ISSUE THREAD

**Issue by scalopus** [brookhong/brookhong.github.io#9]
Usually, keyboard have time interval to repeat the key itself. For example, I try to press Ctrl + Shift + something. When I hold down Ctrl + Shift, the screen will flood of 
Ctrl + Shift
Ctrl + Shift
Ctrl + Shift
Ctrl + Shift
because the keyboard repeat the keys. I hold the key too long such over than a second.

In this case, I think it should be able to show only single
Ctrl + Shift
or be able to ignore to repeat show on the screen with the same key set.

**Comment by brookhong** [comment]
Try latest version 2.0.1.0, and uncheck the setting: `Keyboard Auto Repeat`.
